fix the below error in explorer which "Accept-Language" is not "en-US":
jquery.tablesorter.min.js:4 Uncaught SyntaxError: missing ) after argument list
all.min.js:15 Uncaught TypeError: Cannot read property 'addParser' of undefined
elastichq.js:40 Uncaught TypeError: doFocus is not a function